// <auto-generated />
using System;
using DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbContext.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20260903075724_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("DbModels.FeatureDbM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubscriptionPlanId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("FeatureDbM");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "1 user",
                            SubscriptionPlanId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaab"),
                            Name = "1 social account",
                            SubscriptionPlanId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaac"),
                            Name = "Limited uploads",
                            SubscriptionPlanId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaad"),
                            Name = "Basic analytics",
                            SubscriptionPlanId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbaa"),
                            Name = "Up to 5 users",
                            SubscriptionPlanId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbab"),
                            Name = "Up to 5 social accounts",
                            SubscriptionPlanId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbac"),
                            Name = "Unlimited uploads",
                            SubscriptionPlanId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbad"),
                            Name = "Basic analytics",
                            SubscriptionPlanId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbae"),
                            Name = "Scheduled publishing",
                            SubscriptionPlanId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccca"),
                            Name = "Up to 15 users",
                            SubscriptionPlanId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccb"),
                            Name = "Up to 20 social accounts",
                            SubscriptionPlanId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Name = "Publish to X (Twitter)",
                            SubscriptionPlanId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccd"),
                            Name = "Unlimited uploads",
                            SubscriptionPlanId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccce"),
                            Name = "Advanced analytics",
                            SubscriptionPlanId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccf"),
                            Name = "Scheduled publishing",
                            SubscriptionPlanId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccd0"),
                            Name = "Content management",
                            SubscriptionPlanId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccd1"),
                            Name = "Team collaboration",
                            SubscriptionPlanId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddda"),
                            Name = "Unlimited users",
                            SubscriptionPlanId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddb"),
                            Name = "Unlimited social accounts",
                            SubscriptionPlanId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddc"),
                            Name = "Publish to X (Twitter)",
                            SubscriptionPlanId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Name = "Unlimited uploads",
                            SubscriptionPlanId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddde"),
                            Name = "Advanced analytics",
                            SubscriptionPlanId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddf"),
                            Name = "Scheduled publishing",
                            SubscriptionPlanId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddf0"),
                            Name = "Team collaboration",
                            SubscriptionPlanId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddf1"),
                            Name = "Priority support",
                            SubscriptionPlanId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddf2"),
                            Name = "Custom integrations",
                            SubscriptionPlanId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddf3"),
                            Name = "Dedicated support",
                            SubscriptionPlanId = new Guid("44444444-4444-4444-4444-444444444444")
                        });
                });

            modelBuilder.Entity("DbModels.MediaDbM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("FileContent")
                        .HasColumnType("BLOB");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("DbModels.OrganizationDbM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrganizationSubscriptionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationSubscriptionId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("DbModels.OrganizationInvitationDbM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InviteCode")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvitedEmail")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("OrganizationInvitations");
                });

            modelBuilder.Entity("DbModels.OrganizationSubscriptionDbM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CurrentPeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CurrentPeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubscriptionPlanId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("SubscriptionPlanId");

                    b.ToTable("OrganizationSubscriptions");
                });

            modelBuilder.Entity("DbModels.PostAnalyticsDbM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Comments")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Likes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Shares")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SocialVideoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Views")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SocialVideoId");

                    b.ToTable("PostAnalytics");
                });

            modelBuilder.Entity("DbModels.SocialAccountDbM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("CostumUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("Followers")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSync")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Platform")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("SocialAccounts");
                });

            modelBuilder.Entity("DbModels.SocialVideoDbM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrganizationDbMId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Platform")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProcessingPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("OrganizationDbMId");

                    b.ToTable("SocialVideos");
                });

            modelBuilder.Entity("DbModels.SubscriptionPlanDbM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BillingIntervalInMonths")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ContactSales")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StripePriceId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("isFree")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BillingIntervalInMonths = 1,
                            ContactSales = false,
                            IsActive = true,
                            Name = "Free",
                            Price = 0,
                            isFree = true
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BillingIntervalInMonths = 1,
                            ContactSales = false,
                            IsActive = true,
                            Name = "Basic",
                            Price = 10,
                            StripePriceId = "price_1U8eLiBD6lDY7COkLzS0Q7Vx",
                            isFree = false
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BillingIntervalInMonths = 1,
                            ContactSales = false,
                            IsActive = true,
                            Name = "Pro",
                            Price = 25,
                            StripePriceId = "price_1U3MahBD6lDY7COkvKIK29cg",
                            isFree = false
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            BillingIntervalInMonths = 1,
                            ContactSales = true,
                            IsActive = true,
                            Name = "Enterprise",
                            Price = 0,
                            isFree = false
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            BillingIntervalInMonths = 12,
                            ContactSales = false,
                            IsActive = true,
                            Name = "Basic",
                            Price = 100,
                            StripePriceId = "price_1U8eMABD6lDY7COkoje7yEBw",
                            isFree = false
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            BillingIntervalInMonths = 12,
                            ContactSales = false,
                            IsActive = true,
                            Name = "Pro",
                            Price = 250,
                            StripePriceId = "price_1U3N6rBD6lDY7COkO6ixkp2H",
                            isFree = false
                        });
                });

            modelBuilder.Entity("DbModels.UserDbM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DbModels.UserOrganizationDbM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UserId");

                    b.ToTable("UserOrganizations");
                });

            modelBuilder.Entity("DbModels.FeatureDbM", b =>
                {
                    b.HasOne("DbModels.SubscriptionPlanDbM", "SubscriptionPlanDbM")
                        .WithMany("FeatureDbMs")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionPlanDbM");
                });

            modelBuilder.Entity("DbModels.MediaDbM", b =>
                {
                    b.HasOne("DbModels.OrganizationDbM", "OrganizationDbM")
                        .WithMany("MediaDbMs")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrganizationDbM");
                });

            modelBuilder.Entity("DbModels.OrganizationDbM", b =>
                {
                    b.HasOne("DbModels.OrganizationSubscriptionDbM", "OrganizationSubscriptionDbM")
                        .WithMany()
                        .HasForeignKey("OrganizationSubscriptionId");

                    b.Navigation("OrganizationSubscriptionDbM");
                });

            modelBuilder.Entity("DbModels.OrganizationInvitationDbM", b =>
                {
                    b.HasOne("DbModels.UserDbM", "UserDbM")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbModels.OrganizationDbM", "OrganizationDbM")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrganizationDbM");

                    b.Navigation("UserDbM");
                });

            modelBuilder.Entity("DbModels.OrganizationSubscriptionDbM", b =>
                {
                    b.HasOne("DbModels.OrganizationDbM", "OrganizationDbM")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbModels.SubscriptionPlanDbM", "SubscriptionPlanDbM")
                        .WithMany()
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrganizationDbM");

                    b.Navigation("SubscriptionPlanDbM");
                });

            modelBuilder.Entity("DbModels.PostAnalyticsDbM", b =>
                {
                    b.HasOne("DbModels.SocialVideoDbM", "SocialVideoDbM")
                        .WithMany()
                        .HasForeignKey("SocialVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SocialVideoDbM");
                });

            modelBuilder.Entity("DbModels.SocialAccountDbM", b =>
                {
                    b.HasOne("DbModels.OrganizationDbM", "OrganizationDbM")
                        .WithMany("SocialAccountDbMs")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrganizationDbM");
                });

            modelBuilder.Entity("DbModels.SocialVideoDbM", b =>
                {
                    b.HasOne("DbModels.MediaDbM", "MediaDbM")
                        .WithMany("SocialVideoDbMs")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbModels.OrganizationDbM", null)
                        .WithMany("SocialVideoDbMs")
                        .HasForeignKey("OrganizationDbMId");

                    b.Navigation("MediaDbM");
                });

            modelBuilder.Entity("DbModels.UserOrganizationDbM", b =>
                {
                    b.HasOne("DbModels.OrganizationDbM", "OrganizationDbM")
                        .WithMany("UserOrganizationDbMs")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbModels.UserDbM", "UserDbM")
                        .WithMany("UserOrganizationDbMs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrganizationDbM");

                    b.Navigation("UserDbM");
                });

            modelBuilder.Entity("DbModels.MediaDbM", b =>
                {
                    b.Navigation("SocialVideoDbMs");
                });

            modelBuilder.Entity("DbModels.OrganizationDbM", b =>
                {
                    b.Navigation("MediaDbMs");

                    b.Navigation("SocialAccountDbMs");

                    b.Navigation("SocialVideoDbMs");

                    b.Navigation("UserOrganizationDbMs");
                });

            modelBuilder.Entity("DbModels.SubscriptionPlanDbM", b =>
                {
                    b.Navigation("FeatureDbMs");
                });

            modelBuilder.Entity("DbModels.UserDbM", b =>
                {
                    b.Navigation("UserOrganizationDbMs");
                });
#pragma warning restore 612, 618
        }
    }
}
